### PR TITLE
3.0.1

### PR DESCRIPTION
**Pull request by quasiben**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by quasiben** [comment]
Hmm, these are all failing with an assertion error during build:

```
    File "/home/conda/feedstock_root/build_artifacts/snowflake-connector-python_1678220708991/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "<string>", line 167, in build_extension
    File "<string>", line 202, in _get_arrow_lib_as_linker_input
  AssertionError
  error: subprocess-exited-with-error
```

**Comment by quasiben** [comment]
Making progress but I'm still coming up short.  Snowflake-connector is still trying to link against a particular version of libarrow_python.  Note, I amended setup.py to look for `libarrow_python` in {PREFIX}/iib/python/site-packages/pyarrow as this is where the so installed now:

```
Failed to import ArrowResult. No Apache Arrow result set format can be used. ImportError: libarrow_python.so.1000: cannot open shared object file: No such file or directory
import: 'snowflake.connector.arrow_iterator'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/snowflake-connector-python_1678367109177/test_tmp/run_test.py", line 8, in <module>
    import snowflake.connector.arrow_iterator
ImportError: libarrow_python.so.1000: cannot open shared object file: No such file or directory
```

**Comment by hajapy** [comment]
@quasiben have a look at the changes I was trying in https://github.com/conda-forge/snowflake-connector-python-feedstock/pull/125

specifying the rpaths combined with some of your changes could possibly work 🤞

**Comment by quasiben** [comment]
Thanks @hajapy giving that a try now!

**Comment by quasiben** [comment]
This is mostly working but failing on some arm and windows builds

**Comment by quasiben** [comment]
@hajapy @mariusvniekerk is it possible to re-run just those failing builds ?

**Pull request closed without merging**
